drop table if exists show;
CREATE TABLE show (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"data" varchar(255) NULL,
	data_consegna timestamp NULL,
	des varchar(4000) NULL,
	fonte varchar(255) NULL,
	da varchar(4000) NULL,
	href varchar(1000) NULL,
	img varchar(1000) NULL,
	local_data timestamp NULL,
	titolo varchar(255) NULL,
	CONSTRAINT show_pkey PRIMARY KEY (id)
);

DROP TABLE news;
CREATE TABLE news (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	data_consegna timestamp NULL,
	des varchar(4000) NULL,
	titolo varchar(4000) NULL,
	CONSTRAINT news_pkey PRIMARY KEY (id)
);

drop table if exists logga;
CREATE TABLE logga (
    id serial primary key,
	data timestamp not null,
	log text
);


--ALTER TABLE show ALTER COLUMN img TYPE VARCHAR(1000);